webtalk_init -webtalk_dir C:\\Xilinx\\CECS-461\\Lab_1\\project_1.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jan 30 23:21:03 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7u3vfma7a1bb49d7je471a35n4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.2_5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1517383156926" -context "sdk\\\\hardware/1517383156926"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1517383156926"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1517383156926"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.2" -context "sdk\\\\hardware/1517383156926"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1517383156926"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1517383156926"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1517383156926"
webtalk_add_data -client sdk -key uid -value "1517383181741" -context "sdk\\\\bsp/1517383181741"
webtalk_add_data -client sdk -key hwid -value "1517383156926" -context "sdk\\\\bsp/1517383181741"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1517383181741"
webtalk_add_data -client sdk -key apptemplate -value "memory_tests" -context "sdk\\\\bsp/1517383181741"
webtalk_add_data -client sdk -key uid -value "1517383186331" -context "sdk\\\\application/1517383186331"
webtalk_add_data -client sdk -key hwid -value "1517383156926" -context "sdk\\\\application/1517383186331"
webtalk_add_data -client sdk -key bspid -value "1517383181741" -context "sdk\\\\application/1517383186331"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1517383186331"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1517383186331"
webtalk_add_data -client sdk -key apptemplate -value "memory_tests" -context "sdk\\\\application/1517383186331"
webtalk_transmit -clientid 1063740657 -regid "" -xml C:\\Xilinx\\CECS-461\\Lab_1\\project_1.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Xilinx\\CECS-461\\Lab_1\\project_1.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Xilinx\\CECS-461\\Lab_1\\project_1.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
