# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/hardware_linux/hardware_linux.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_linux || ORIG_REF_NAME==hardware_linux}]

# IP: bd/hardware_linux/ip/hardware_linux_processing_system7_0_0/hardware_linux_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardware_linux_processing_system7_0_0 || ORIG_REF_NAME==hardware_linux_processing_system7_0_0}]

# XDC: bd/hardware_linux/ip/hardware_linux_processing_system7_0_0/hardware_linux_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hardware_linux_processing_system7_0_0 || ORIG_REF_NAME==hardware_linux_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/hardware_linux/hardware_linux_ooc.xdc
