webtalk_init -webtalk_dir C:\\Xilinx\\CECS-461\\Lab_2\\project_2\\project_2.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Feb 1 07:53:14 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6ujnot1b4qsf71en7gdjkba2lk" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.2_7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1517499130755" -context "sdk\\\\bsp/1517499130755"
webtalk_add_data -client sdk -key hwid -value "1517497584802" -context "sdk\\\\bsp/1517499130755"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1517499130755"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1517499130755"
webtalk_add_data -client sdk -key uid -value "1517499186097" -context "sdk\\\\application/1517499186097"
webtalk_add_data -client sdk -key hwid -value "1517497584802" -context "sdk\\\\application/1517499186097"
webtalk_add_data -client sdk -key bspid -value "1517499130755" -context "sdk\\\\application/1517499186097"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1517499186097"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1517499186097"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1517499186097"
webtalk_add_data -client sdk -key uid -value "1517499212623" -context "sdk\\\\application/1517499212623"
webtalk_add_data -client sdk -key hwid -value "1517497584802" -context "sdk\\\\application/1517499212623"
webtalk_add_data -client sdk -key bspid -value "1517499130755" -context "sdk\\\\application/1517499212623"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1517499212623"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1517499212623"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1517499212623"
webtalk_transmit -clientid 1842147134 -regid "" -xml C:\\Xilinx\\CECS-461\\Lab_2\\project_2\\project_2.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Xilinx\\CECS-461\\Lab_2\\project_2\\project_2.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Xilinx\\CECS-461\\Lab_2\\project_2\\project_2.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
